In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,6,8,4,3])  # usually we assing

In [3]:
myarr

array([2, 3, 6, 8, 4, 3])

In [4]:
myarr[1]

3

In [5]:
myarr[0]

2

In [6]:
myarr[5]

3

In [7]:
myarr.shape

(6,)

#### use of np.int  
this is use to specify the size of our array

In [8]:
myarr = np.array([2,3,6,8,4,3], np.int8)

In [9]:
myarr  #now this is a 8 bit array 

array([2, 3, 6, 8, 4, 3], dtype=int8)

In [10]:
myarr = np.array([2,3,6,8,4,3] , np.int16)
myarr   # this is a 16 bit array

array([2, 3, 6, 8, 4, 3], dtype=int16)

In [11]:
myarr = np.array([2,3,6,8,4,3], np.int64)   # we can make it of 8,16,32,or 64 bit depends on our data size 
myarr

array([2, 3, 6, 8, 4, 3], dtype=int64)

In [12]:
myarr.dtype   # to know the data type

dtype('int64')

In [13]:
myarr = np.array([4.3,2.6,7,9.0,8], np.int32) # we have float value here so , we need to give it np.flot32 or 64,16,8

In [14]:
myarr   # the number has been changed to int ,,, we need to give it float 

array([4, 2, 7, 9, 8])

In [15]:
myarr = np.array([4.3,2.6,7,9.0,8], np.float64) # for float values
myarr  # here the number will not change into int , it will be in float 

array([4.3, 2.6, 7. , 9. , 8. ])

In [16]:
myarr[0]

4.3

In [17]:
myarr[0] = 10.5 # now the number will be changed 
myarr[0]

10.5

In [18]:
# see the above number has been chaged form 4.3 to 10.5

## Array creation 

In [19]:
Larray = np.array([[3,4.1,5],[2,5,9.2],[33,5,7]])   # a 3D array form a list 

In [20]:
Larray

array([[ 3. ,  4.1,  5. ],
       [ 2. ,  5. ,  9.2],
       [33. ,  5. ,  7. ]])

In [21]:
Larray.dtype

dtype('float64')

In [22]:
Larray.shape

(3, 3)

In [23]:
Larray.size

9

***Zeros***

In [24]:
zarray = np.zeros((2,6))  
# this will create a array of 2 rows and 6 columns , filled with zeros


In [25]:
zarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
print(zarray.shape)
print(zarray.dtype)
zarray.size

(2, 6)
float64


12

***arange***   (from a range )

In [27]:
rng = np.arange(25)  # it will give you a array of range 25 (0 to 24)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

***linspace*** (linear space)

In [29]:
lspace = np.linspace(1,5,10)   
## this will give you a array of 10 element form 1 to 5 of equal space(dif) between no.
#see bellow 
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [30]:
llspace = np.linspace(1,50,10)
llspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
lllspace = np.linspace(1,4,4)
lllspace

array([1., 2., 3., 4.])

***empty***

In [32]:
emp = np.empty((2,4))   
#this will give a empty array of shape 2,4 with random elements , letter on we can assing any value to this 
#see bellow 
emp

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 7.35e-321, 0.00e+000, 0.00e+000]])

In [33]:
emp_like = np.empty_like(lllspace)  # this will create a empty array like lllspace 
emp_like

array([1., 2., 3., 4.])

***identity***

In [34]:
ide = np.identity(10)
ide
#this will give 10*10 array of identity 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
ide.shape 

(10, 10)

***reshape***

In [36]:
arrr = np.arange(75)
arrr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [37]:
arrr = arrr.reshape(3,25)  # Now reshaping the above value in 3 rows and 25 columns or 3*25
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74]])

***ravel***

In [38]:
arrr = arrr.ravel()   #this function will make it into 1D array 
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [39]:
arrr.shape

(75,)

### axis of array 

In [40]:
x = [[2,4,3],[5,6,4],[7,8,9]]
ar = np.array(x)
ar

array([[2, 4, 3],
       [5, 6, 4],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0)   # up to down 

array([14, 18, 16])

In [42]:
ar.sum(axis=1) # right to left

array([ 9, 15, 24])

In [43]:
ar.T # it will transpose the array 

array([[2, 5, 7],
       [4, 6, 8],
       [3, 4, 9]])

In [44]:
 ar.flat  # flat 

In [45]:
for item in ar.flat:
    print(item)

2
4
3
5
6
4
7
8
9


In [46]:
ar

array([[2, 4, 3],
       [5, 6, 4],
       [7, 8, 9]])

In [47]:
ar.ndim # give the dimenstion of array

2

In [48]:
ar.size # give the size of the array 

9

In [49]:
ar.nbytes # tells total bytes consumed by our array 

36

In [50]:
one = np.array([2,6,44,99])  # creating a 1D array 
one

array([ 2,  6, 44, 99])

In [51]:
one.argmax() # will tell the index place having higher value 

# in our array we have higher value at index 3 

3

In [52]:
one.argmin()  # will tell the idex having lower value 

0

In [53]:
one.argsort()  # will tell the index no. ,, lower to higher value 

array([0, 1, 2, 3], dtype=int64)

In [55]:
ar    # for 2D array

array([[2, 4, 3],
       [5, 6, 4],
       [7, 8, 9]])

In [56]:
ar.argmax()    # it will consider as flat and will give values based on that 

8

In [57]:
ar.argmin()

0

In [59]:
ar.argmax(axis=0)   

array([2, 2, 2], dtype=int64)

In [60]:
# in the first row max value at index 2, for secound row it's 2, same for the 3. that's why above result is 222

In [61]:
ar.argmin(axis=1)

array([0, 2, 0], dtype=int64)

In [62]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [63]:
# above telling the idex , which need to array be sort

In [65]:
ar.argsort(axis=1)

array([[0, 2, 1],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [66]:
ar.shape

(3, 3)

In [68]:
ar.ravel()

array([2, 4, 3, 5, 6, 4, 7, 8, 9])

In [69]:
ar

array([[2, 4, 3],
       [5, 6, 4],
       [7, 8, 9]])

In [71]:
ar2 = np.array([[2,4,5],[5,8,0],[11,22,33]])
ar2

array([[ 2,  4,  5],
       [ 5,  8,  0],
       [11, 22, 33]])

In [72]:
ar+ar2

array([[ 4,  8,  8],
       [10, 14,  4],
       [18, 30, 42]])

In [73]:
# it has added the value of same index

In [74]:
ar*ar2

array([[  4,  16,  15],
       [ 25,  48,   0],
       [ 77, 176, 297]])

In [78]:
np.sqrt(ar) # this will squar root of array  

array([[1.41421356, 2.        , 1.73205081],
       [2.23606798, 2.44948974, 2.        ],
       [2.64575131, 2.82842712, 3.        ]])

In [82]:
ar

array([[2, 4, 3],
       [5, 6, 4],
       [7, 8, 9]])

In [79]:
ar.max()

9

In [80]:
ar.min()

2

In [81]:
ar.sum()

48

In [83]:
np.where(ar>5)  # will give the index no. where values is gr than 5 ,, this index will be in tuple

(array([1, 2, 2, 2], dtype=int64), array([1, 0, 1, 2], dtype=int64))

In [85]:
type(np.where(ar>5))  # see it's a tuple 

tuple

In [ ]:
np.count_nonzero(ar)  # will give the count of non zero elements

In [89]:
ar[1,2] = 0          # changing 1,2 idex value to zero , then counting
np.count_nonzero(ar)

8

In [101]:
ar

array([[2, 4, 3],
       [5, 6, 0],
       [7, 8, 9]])

In [103]:
ar3 = np.array([1,2,3])

In [105]:
C= np.dot(ar3,ar)  
C

array([33, 40, 30])

In [107]:
d = np.dot(ar,ar2)
d

array([[ 57, 106, 109],
       [ 40,  68,  25],
       [153, 290, 332]])

In [109]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

### size different of python list and np

In [91]:
import sys 

In [95]:
py_ar = [11,22,33,66,55,44,99]    # python arrray or list  

In [97]:
sys.getsizeof(1)*len(py_ar)

196

In [98]:
np_ar = np.array(py_ar)           # np array of same element

In [99]:
np_ar.itemsize*np_ar.size

28